auditbeat.modules:

- module: system
  datasets:
    - host
    - login
    - package
    - user
  period: 1m
  user.detect_password_changes: true

- module: system
  datasets:
    - process
    - socket
  period: 1s


output.elasticsearch:
  hosts: ["192.168.50.4:9200"]

setup.kibana:
  host: "192.168.50.4:5601"


# vagrant ssh grafana
# apt-get install auditbeat
# vi audit_beat.yml
# auditbeat setup --dashboards -e
# auditbeat run -c /root/audit_beat.yml -e
# go to kibana and see the data

